# Generated by Django 3.2.3 on 2021-11-23 18:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABC_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Correct_Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('descrpition', models.TextField(blank=True)),
                ('date_time_creations', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='media/images/')),
                ('page_order', models.TextField()),
                ('filled_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Filled_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_filled', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('courses', models.ManyToManyField(to='main.Filled_Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('date_time_creations', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Recovery_Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_creations', models.DateTimeField(auto_now=True)),
                ('valid_thru', models.DateTimeField(default=datetime.datetime(2021, 12, 23, 18, 44, 56, 661767))),
                ('secret_key_1', models.TextField()),
                ('secret_key_2', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page_in_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date_time_creations', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('task', models.TextField()),
                ('solution', models.FileField(blank=True, upload_to='media/solutions/')),
                ('solution_text', models.TextField(blank=True)),
                ('show_correct', models.BooleanField(default=True)),
                ('inputs', models.TextField(blank=True)),
                ('task_or_question', models.CharField(choices=[('t', 'task'), ('q', 'question'), ('c', 'abc')], default='t', max_length=1)),
                ('abc_values', models.ManyToManyField(blank=True, to='main.ABC_choices')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('correct', models.ManyToManyField(to='main.Correct_Choices')),
            ],
        ),
        migrations.CreateModel(
            name='Filled_Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_filled', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, upload_to='media/py_files/')),
                ('solution_text', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page_in_course')),
            ],
        ),
        migrations.AddField(
            model_name='filled_course',
            name='pages',
            field=models.ManyToManyField(to='main.Filled_Pages'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Návrh na vylepšení', 'Návrh na vylepšení'), ('Problém', 'Problém'), ('Něco jiného', 'Něco jiného')], default='Návrh na vylepšení', max_length=18)),
                ('text', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='pages',
            field=models.ManyToManyField(blank=True, to='main.Page_in_course'),
        ),
    ]
