# Generated by Django 3.2.3 on 2021-11-23 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery_password',
            name='valid_thru',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 18, 46, 1, 100730)),
        ),
    ]
