# Generated by Django 3.2.3 on 2022-02-10 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recovery_password_valid_thru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery_password',
            name='valid_thru',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 21, 45, 25, 504140)),
        ),
    ]
